(function () {
  "use strict";

  const config = window.DRAMA_CONFIG;
  const original = clone(config);
  const preview = document.getElementById("editor-preview");

  const fields = {
    night: ["theme", "night"],
    paper: ["theme", "paper"],
    rose: ["theme", "rose"],
    "korean-font": ["fonts", "korean"],
    "english-font": ["fonts", "english"],
    "display-font": ["fonts", "display"],
    "names-left": ["landing", "namesLeft"],
    "names-right": ["landing", "namesRight"],
    "title-line": ["landing", "titleLine"],
    "title-accent": ["landing", "titleAccent"],
    "title-end": ["landing", "titleEnd"],
    "button-copy": ["landing", "button"],
    "landing-image": ["images", "landing", "src"],
    "emma-image": ["images", "characters", "emma"],
    "charlie-image": ["images", "characters", "charlie"],
    "rachel-image": ["images", "characters", "rachel"],
    "mike-image": ["images", "characters", "mike"],
  };

  Object.keys(fields).forEach(function (id) {
    const input = document.getElementById(id);
    if (!input) return;
    input.value = readValue(fields[id]);
    input.addEventListener("input", function () {
      writeValue(fields[id], input.value);
      renderPreview();
    });
  });

  document.getElementById("download-config").addEventListener("click", downloadConfig);
  document.getElementById("reset-editor").addEventListener("click", resetEditor);
  renderPreview();

  function readValue(path) {
    return path.reduce(function (value, key) { return value[key]; }, config);
  }

  function writeValue(path, value) {
    const last = path[path.length - 1];
    const parent = path.slice(0, -1).reduce(function (object, key) { return object[key]; }, config);
    parent[last] = value;
  }

  function renderPreview() {
    const root = document.documentElement;
    root.style.setProperty("--night", config.theme.night);
    root.style.setProperty("--paper", config.theme.paper);
    root.style.setProperty("--rose", config.theme.rose);
    root.style.setProperty("--font-korean", config.fonts.korean);
    root.style.setProperty("--font-english", config.fonts.english);
    root.style.setProperty("--font-display", config.fonts.display);

    document.getElementById("preview-names-left").textContent = config.landing.namesLeft;
    document.getElementById("preview-names-right").textContent = config.landing.namesRight;
    document.getElementById("preview-title-line").textContent = config.landing.titleLine;
    document.getElementById("preview-title-accent").textContent = config.landing.titleAccent;
    document.getElementById("preview-title-end").textContent = config.landing.titleEnd;
    document.getElementById("preview-button").firstChild.textContent = `${config.landing.button} `;
    const landingImage = document.getElementById("preview-landing-image");
    const landingImageElement = landingImage.querySelector("img");
    landingImage.classList.toggle("is-visible", Boolean(config.images.landing.src));
    landingImageElement.src = config.images.landing.src || "";
    preview.style.background = config.theme.night;
    preview.style.color = config.theme.paper;
  }

  function downloadConfig() {
    const file = `/* Generated by editor.html. Replace the existing site-config.js with this file. */\nwindow.DRAMA_CONFIG = ${JSON.stringify(config, null, 2)};\n`;
    const blob = new Blob([file], { type: "text/javascript;charset=utf-8" });
    const link = document.createElement("a");
    link.download = "site-config.js";
    link.href = URL.createObjectURL(blob);
    link.click();
    URL.revokeObjectURL(link.href);
  }

  function resetEditor() {
    Object.keys(config).forEach(function (key) { delete config[key]; });
    Object.assign(config, clone(original));
    Object.keys(fields).forEach(function (id) {
      document.getElementById(id).value = readValue(fields[id]);
    });
    renderPreview();
  }

  function clone(value) {
    return JSON.parse(JSON.stringify(value));
  }
})();
