(function () {
  "use strict";

  const config = window.DRAMA_CONFIG;
  const original = JSON.parse(JSON.stringify(config));
  const slots = [
    { key: "landing", label: "첫 화면 이미지", code: "LANDING" },
    { key: "emma", label: "엠마 결과 이미지", code: "EMMA" },
    { key: "charlie", label: "찰리 결과 이미지", code: "CHARLIE" },
    { key: "rachel", label: "레이첼 결과 이미지", code: "RACHEL" },
    { key: "mike", label: "마이크 결과 이미지", code: "MIKE" },
  ];
  const slotRoot = document.getElementById("image-slots");
  const previewRoot = document.getElementById("preview-grid");

  renderSlots();
  renderPreview();

  document.getElementById("download-config").addEventListener("click", downloadConfig);
  document.getElementById("clear-images").addEventListener("click", clearImages);

  function renderSlots() {
    slotRoot.innerHTML = slots.map(function (slot) {
      return `<label class="image-slot" for="file-${slot.key}">
        <span><strong>${slot.label}</strong><small>${slot.code}</small></span>
        <input id="file-${slot.key}" type="file" accept="image/*" data-image-key="${slot.key}" />
        <span class="slot-status" id="status-${slot.key}">${hasImage(slot.key) ? "이미지가 선택되어 있어요." : "아직 선택한 이미지가 없어요."}</span>
      </label>`;
    }).join("");

    slots.forEach(function (slot) {
      document.getElementById(`file-${slot.key}`).addEventListener("change", function (event) {
        const file = event.target.files[0];
        if (!file) return;
        const reader = new FileReader();
        reader.addEventListener("load", function () {
          setImage(slot.key, reader.result);
          document.getElementById(`status-${slot.key}`).textContent = `${file.name} 선택 완료`;
          renderPreview();
        });
        reader.readAsDataURL(file);
      });
    });
  }

  function renderPreview() {
    previewRoot.innerHTML = slots.map(function (slot) {
      const source = getImage(slot.key);
      return `<figure class="preview-card">${source ? `<img src="${source}" alt="${slot.label}" />` : ""}<span>${slot.code}</span></figure>`;
    }).join("");
  }

  function setImage(key, source) {
    if (key === "landing") {
      config.images.landing.src = source;
    } else {
      config.images.characters[key] = source;
    }
  }

  function getImage(key) {
    return key === "landing" ? config.images.landing.src : config.images.characters[key];
  }

  function hasImage(key) {
    return Boolean(getImage(key));
  }

  function clearImages() {
    config.images = JSON.parse(JSON.stringify(original.images));
    renderSlots();
    renderPreview();
  }

  function downloadConfig() {
    const file = `/* Generated by image-manager.html. Replace the existing site-config.js with this file. */\nwindow.DRAMA_CONFIG = ${JSON.stringify(config, null, 2)};\n`;
    const blob = new Blob([file], { type: "text/javascript;charset=utf-8" });
    const link = document.createElement("a");
    link.download = "site-config.js";
    link.href = URL.createObjectURL(blob);
    link.click();
    setTimeout(function () { URL.revokeObjectURL(link.href); }, 1000);
  }
})();
